name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    # Runs every 4 hours (adjust as needed, e.g. "0 * * * *" for every hour)
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-solutions
          verbose: true
          commit-header: "[LeetCode Sync]"
